//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Poslednijj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// УдКл.
    /// </summary>
    // *** Start programmer edit section *** (УдКл CustomAttributes)

    // *** End programmer edit section *** (УдКл CustomAttributes)
    public enum УдКл
    {
        
        // *** Start programmer edit section *** (УдКл.Удовлетворен CustomAttributes)

        // *** End programmer edit section *** (УдКл.Удовлетворен CustomAttributes)
        [Caption("Удовлетворен")]
        Удовлетворен,
        
        // *** Start programmer edit section *** (УдКл.НеУдовлетвор CustomAttributes)

        // *** End programmer edit section *** (УдКл.НеУдовлетвор CustomAttributes)
        [Caption("Не удовлетворен")]
        НеУдовлетвор,
    }
}
